:Author: ibfleming
:Email: flem8015@vandals.uidaho.edu
:Date: 18/03/2023
:Revision: 1.0.0
:License: Public Domain

= Project: Stream Velocity Measuring Device

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 MasterNano                => Arduino sketch folder
  ├── MasterNano.ino       => main, Master Nano Arduino file
  ├── SlaveNano.ino        => Slave Nano Arduino file
  └── ReadMe.adoc          => this file, documentation
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ibfleming https://id.arduino.cc/ibfleming

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| 1  | Arduino Nano   | xxx         | 2
| 2  | HC-10 BT       | xxx         | 1
| 3  | HC-06 BT       | xxx         | 1
| 4  | TDS Meter      | xxx         | 2
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
